### ISSUE TITLE
Decide high level strategy for 3ID auth

### ISSUE THREAD

**Issue by oed** [3box/3box#1000]
Coordinate with @michaelsena and maybe @oed about requirements, and how people can add support for themselves?

**Comment by zachferland** [comment]
Will not look too different than the approach of adding account links in 3id-blockchain-utils, except that you implement an authprovider (which may be a single auth function). Maybe go in 3id-blockchain-utils as well, and then imported into 3id-connect along with the account link implementation, unless testing/implementation a lot easier directly in 3id-connect. 

Possible auth provider, object/class implements single function. Similar to current form just not strictly a web3 provider interface. 

```
// consume message string
// returns 32-64 bytes entropy, hex string, and maybe an accountId (address or other id) 
// only requirement is each message + account deterministically maps to one unique output

authenticate(message) {
   // import reference any providers, accounts etc and setup 
   // could be some iframe/modal, something injected somewhere etc 
   // for given message (& accountId) return hex string 
  //  for most this will be signing message with blockchain provider,  but does not strictly have to hold
} 
```
Future considerations may included redirect flows, error handling, if a separate setup/connect function will have any use. 

In 3id connect, a config object would be passed and added to the set of supported providers. This would include reference to auth provider and link methods. Then would include some meta data like providerId, providerImage, possibly some network/chainid. 

This will all be strictly defined after and goal will be minimize difficulty for someone to add support for a method and way for us to easily maintain (testing, comms channel, etc)
