### ISSUE TITLE
look into additional ghostthread impovements

### ISSUE THREAD

**Issue by oed** [3box/3box#1063]
If using only a bootstrap node is too slow.

**Comment by simonovic86** [comment]
@oed do we need to look into additional improvements? according to tests, using the bootstrap node has satisfying improvements.

**Comment by oed** [comment]
Yep, no need to!

**Comment by simonovic86** [comment]
> Yep, no need to!

👍

**Comment by simonovic86** [comment]
according to tests, using the bootstrap node has satisfying improvements and we don't need to look into additional improvements.
