### ISSUE TITLE
Cannot find 'catch' of undefined and cannot set property 'set' of null.

### ISSUE THREAD

**Issue by rachit2501** [3box/3box#1072]
**Bug**
Getting two errors: cannot read catch of undefined, and cannot call property "set" of null.

**Expected behavior**
No such error should appear. `box.public` should exist.

Response Object on Box.create:
```
Box {_provider: undefined, _ipfs: Proxy, _serverUrl: "https://beta.3box.io/address-server", public: null, private: null, …}
hasPublishedLink: {}
private: null
public: null
replicator: Replicator {events: EventEmitter, ipfs: Proxy, _pinningNode: ClassIsWrapper, _stores: {…}, _storePromises: {…}, …}
spaces: {}
syncDone: null
verified: Verified {_box: Box}
_3id: ThreeId {events: EventEmitter, _provider: ThreeIdProviderProxy, _has3idProv: true, _ipfs: Proxy, _muportIpfs: {…}, …}
_3idEthAddress: "0x06fd9d0ae9052a85989d0a30c60fb11753537f9a"
_ipfs: Proxy {bitswap: {…}, block: {…}, bootstrap: {…}, add: ƒ, cat: ƒ, …}
_provider: ThreeIdProviderProxy {is3idProvider: true, threeIdConnect: true, migration: true, postMessage: ƒ, sendRPC: ƒ}
_serverUrl: "https://beta.3box.io/address-server"
DID: (...)
__proto__: BoxApi
```
**Screenshots**
[](https://i.imgur.com/Ab2Y2Ni.png)

 - OS: Ubuntu
 - Browser Chrome
 - Version 83

**Comment by oed** [comment]
Hey @rachit2501 Can you share some more details of your issue? Maybe share some code where it's breaking?

**Comment by valmack** [comment]
@oed Also had same issue as @rachit2501 we were trying to debug but I'm wondering if there is some issue on the MetaMask side over the past few days that could be leading to this.

Here is my implementation that works but produces the error: https://gist.github.com/valmack/f401662c1f44c1ed359c29160c719b68

**Comment by rachit2501** [comment]
Yes!!. Though I cannot seem to imagine how can metamask cause these errors,

**Comment by oed** [comment]
Thanks for the update @rachit2501 The latest version of 3box-js should use `libp2p-pubsub@0.4.6` by default to get around this issue. Closing this :)

**Comment by rachit2501** [comment]
no . That only resolved one issue . Box are still not being created.

**Comment by oed** [comment]
Ok, @rachit2501 Can you please describe how to replicate the issue?

**Comment by rachit2501** [comment]
Yes!!. Sure. All you need to do is run the code available on the gist above. Just keep the version of metamask and web3 up to date. You will see that the box returned on `Box.create` has most of the entries null.

**Comment by oed** [comment]
@rachit2501 just quickly looking at the code above it looks like the `web3` object might not be set if `window.ethereum` isn't present?

**Comment by rachit2501** [comment]
@oed No. I crossed checked. On my system, `window.ethereum` is defined and web3 setup is also working fine.

**Comment by oed** [comment]
My guess is that there is some promise that you forget to await somewhere. It's hard to say for sure though without seeing all of your code.

**Comment by rachit2501** [comment]
I actually re-implemented the code above only. The same issue is occurring in that also. I also think maybe it has something to do with the metamask version maybe.

**Comment by oed** [comment]
@rachit2501 Try to see if you are doing something differently from the [example provided here](https://github.com/3box/3box-js/tree/develop/example) maybe?

**Comment by rachit2501** [comment]
I tried using the same code. Maybe the issue is because of metamask version.
