### ISSUE TITLE
Use js-ipfs in anchor service

### ISSUE THREAD

**Issue by oed** [3box/3box#1108]
See if we can enable the DHT.

**Comment by simonovic86** [comment]
@oed CAS uses go-ipfs instance deployed on our infrastructure at the moment. The best approach is to replace that instance with js-ipfs, right?

**Comment by oed** [comment]
Exactly.

**Comment by simonovic86** [comment]
I think we underestimated the story 😊

**Comment by simonovic86** [comment]
Blocked by this [IPFS issue](https://github.com/ipfs/js-ipfs/issues/3300) that I've created.
