### ISSUE TITLE
Demo 3Box is not running

### ISSUE THREAD

**Issue by antontranelis** [3box/3box#1167]
**Describe the bug**
When I press Button "Get Started" after signing transaction in MetaMask nothing happens

**To Reproduce**
1. Go to https://3chat.3box.io/
2. Click on Get Started
3. Login with MetaMask
4. Nothing happens

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 81.0

**Comment by oed** [comment]
Sorry, this demo is no longer being maintained.
