### ISSUE TITLE
Create anchor service monitoring dashboards

### ISSUE THREAD

**Issue by valmack** [3box/3box#1211]

**Comment by valmack** [comment]
All requests per second
- just counts the http requests but doesn't separate beyond that

![Screen Shot 2020-12-17 at 8.06.50 AM.png](https://images.zenhubusercontent.com/5e4518ac503aa45865db188a/d079cec2-134f-4eae-b22a-16572a88e776)

All requests to `/requests`
- shows requests by origin or requests by status code
![Screen Shot 2020-12-17 at 8.09.40 AM.png](https://images.zenhubusercontent.com/5e4518ac503aa45865db188a/67c53dba-c4cb-4130-8651-68faa3b90441)

All pots requests to `/anchors`

Eth balance
- haven't been able to see it yet because it is only captured when a tx is made

**Comment by oed** [comment]
Looks good at a glance.

For the first few graphs, I assume we will be able to see failed vs successful requests? Is there a way to either count failed ones, or see a %?

For *Anchor request statuses* is it possible to also see the DocID?
