### ISSUE TITLE
Remove doctype from genesis record

### ISSUE THREAD

**Issue by oed** [3box/3box#1220]

**Comment by stbrody** [comment]
@oed why would we remove doctype from the genesis record?  How else would you know what doctype a document is?  The spec does seem to say that the GenesisRecord includes the doctype

**Comment by oed** [comment]
The doctype is now encoded in the new DocID format. Previously this was not the case. The spec needs to be updated to reflect this.

**Comment by stbrody** [comment]
Right, okay I forgot that.  It means that two documents can have the same genesis record with different doctypes, but that's probably fine.  Thanks for clarifying!
