### ISSUE TITLE
Use RESPONSE message type for document query responses

### ISSUE THREAD

**Issue by oed** [3box/3box#1222]
Should be defined in the CIP.

**Comment by stbrody** [comment]
Just want to confirm, we we want to use the RESPONSE type for *requests*?  Not for responses?  @oed

**Comment by oed** [comment]
There is a description of how this should work here: https://github.com/ceramicnetwork/ceramic/blob/master/SPECIFICATION.md#queries

**Comment by stbrody** [comment]
Should be the new RESPONSE message type as specified in [CIP-71](https://github.com/ceramicnetwork/CIP/blob/master/CIPs/CIP-71/CIP-71.md)

**Comment by stbrody** [comment]
Fixed by https://github.com/ceramicnetwork/js-ceramic/pull/542
