### ISSUE TITLE
Implement and test gas estimation for ropsten & mainnet

### ISSUE THREAD

**Issue by oed** [3box/3box#1223]
Handle gas limit/price and possible failures in the CAS.

**Comment by valmack** [comment]
I was wondering if it makes sense to try and simulate on a fork, and if that would help with gas estimations but I think it is still not very reliable

**Comment by simonovic86** [comment]
**TLDR of the research and experimentation**

I was getting `gasPrice` in three different ways:
* etherscan API
* ethgasstation API
* `ethers.js` default provider for `mainnet`/`ropsten` (`homestead`/`ropsten`)

My conclusion is that we can safely use `provider.getGasPrice()` from `ethers.js`. The values which we get are similar to the `avarage` ones on https://etherscan.io/gastracker.
