### ISSUE TITLE
Refine infra deployment pipline

### ISSUE THREAD

**Issue by oed** [3box/3box#1269]
Sync on exactly what this should look like.

Expectations for different nodes and how we should use them

How can we automate, what order to do update 3id-connect, infra, etc?
How do we test the releases and move them to public facing environments?

**Comment by valmack** [comment]
Leaving this discord comment from Paul

> Due to the dependencies we can't have sync releases of the entire stack at once, we need to do Ceramic, then IDX and finally 3ID Connect in order, then we can update the demos and tutorials.

**Comment by valmack** [comment]
Luckily we talked a bit about this today

- want to deploy release candidates to testnet/clay before things go to prod/mainnet

**Comment by valmack** [comment]
Closing as this will be more detailed in our CD project
