### ISSUE TITLE
Setup external facing node for external devs (testnet-clay)

### ISSUE THREAD

**Issue by oed** [3box/3box#1272]
Change what is currently "ceramic-dev" to "ceramic-testnet" and create an internal dev environment
- deploy environments
- update dns

**Comment by dazuck** [comment]
I'm completely fine if the answer is "No" to this, but want to ask --

If we're concerned about setting precedent of us providing public nodes
(which has been raised a few times), do we want to do something to temper
off the bat? Rate limiting or requiring registration for API keys (or a
combo)? Fine if we choose to do the bare minimum first but want to at least
do so consciously.

**Comment by valmack** [comment]
Creating another story for rate limiting
