### ISSUE TITLE
Add transition banner to 3Box.io or 3Boxlabs.com*

### ISSUE THREAD

**Issue by dazuck** [3box/3box#1293]

**Comment by dazuck** [comment]
@michaelsena I'm adding this as it was in "Additional Work" to add a banner to 3box.io in the sprint plan, but I thought the plan was to (a) redirect 3box.io to 3boxlabs, (b) keep 3box.io/hub hosted, and (c) have a banner or popup on 3boxlabs.com explaining it? 

Whatever is the plan, can you update the story? I think it should be a redirect b/c keeping 3Box.io up even though we're trying to direct ppl to idx seems confusing. If we keep it, it should at least be a large banner/popup IMO.

**Comment by oed** [comment]
duplicate.
