### ISSUE TITLE
Move js-ipfs-ceramic into js-ceramic monorepo

### ISSUE THREAD

**Issue by oed** [3box/3box#1313]
it likely also makes sense to rename the package to `js-ipfs-jose`.

**Comment by stbrody** [comment]
> it likely also makes sense to rename the package to `js-ipfs-jose`.

Currently at least the package does more than supply dag-jose support, it also disables the DHT and has our ceramic-specific logic for connecting to our infra nodes and the nodes from the bootstrap list.

**Comment by oed** [comment]
Good point. maybe the package should be called just `@ceramicnetwork/ipfs`?

**Comment by stbrody** [comment]
> Good point. maybe the package should be called just `@ceramicnetwork/ipfs`?

Will that be a problem if/when we have new custom code for interacting with `go-ipfs`?  Will it definitely be able to go into the same repo, or might it need its own repo to conform to go repo layout standards?

**Comment by oed** [comment]
The custom code for go-ipfs would likely not live in the typescript monorepo.

**Comment by stbrody** [comment]
Yeah okay that makes sense.  And if there's custom javascript code for interacting with a remote go-ipfs node over http, then it probably *would* live in this repo, so naming it `@ceramicnetwork/ipfs` seems right, rather than including `js` in the name
