### ISSUE TITLE
Define data provided and expected back by 3ID Connect to Management app

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1319]

**Comment by PaulLeCam** [comment]
Here is the data I started the implementation with: https://github.com/ceramicstudio/3id-connect-management/blob/main/src/types.ts#L6-L10
The `dids` being a record of DID to CAIP-10 accounts () the user could choose to create the link (assuming it could be more than one?) and the `linkToDID` being the DID string to create the link proof to, assuming it's the goal of this app?

**Comment by zachferland** [comment]
Ok so this implementation went the path of an entirely stand alone app for these account linking/creating screens and providers vs app in 3id-connect and separate app for providers, right? 

Then we need to define data here and transport (depending on exactly how configured) 

So on load in management app, minimally need list of dids currently available in 3id-connect. And can also be a record of did to caip10. Currently 3id-connect caip10 list state doesn't reflect most recent links in network, may make sense to lookup links instead. 

Then in response, the following flows happen. (unless fewer where prioritized for now) 

1) user wants to link current (authprovider caip10), then this can just return linktoDID, 3id-connect can still use authprovider in parent window to create a link proof 

2) user after initializing account management decides they actually just want to create new account still. In this case can just return to 3id-connect, and 3id-connect can use authprovider in parent window to get authsecret and linkproof. Better ui flow might have some more facilitated through management app using something similar to next flow. 

3) user wants to link current (authprovider caip10), to an account that doesnt exist in 3id-connect iframe. This being the complex flow an most unclear. So they use a provider/authprovider in management app, create a did (ie authsecret, linkproof). And then returning to 3id-connect with new did for linkToDID, 3id-connect itself can get link proof for new did from authprovider in parent window. A few options here, but dont feel like i can make concrete until live sync, to make sure im understanding direction of management app correctly so far, can ping in my morning. 

Anyway, it seems like it will make sense to have a standard interface to the state/storage in 3id-connect now. Then that can be shared over a permissioned rpc layer or the same interface can just be directly exposed to an app on the same domain. 

As we mentioned in past calls, the quickest/simplest path for this still would be to have this app on the same (3id-connect) domain. It would then have a shared library with 3id-connect for a few calls and a shared state/storage interface for the core data there now (ie dids, authsecrets, etc). Of course this comes with the security tradeoffs, which we can then mitigate in future iterations by moving parts to other domains. One proposal was just moving out all the providers for example (or entire app still). But either way with interfaces above( shared lib, state/storage), not much would change hopefully, just they would be over some rpc calls and relayed/permissioned as needed (depending on configuration)

**Comment by PaulLeCam** [comment]
> Ok so this implementation went the path of an entirely stand alone app for these account linking/creating screens and providers vs app in 3id-connect and separate app for providers, right?

So far I made this app assuming it would only be the "app for providers", so only supporting the flow 3, but as you wrote I'm not clear on how this flow works, so the current implementation of the management app probably doesn't work for this. I thought the management app would only need to create a link proof, but you wrote here it should actually create the DID?

> Anyway, it seems like it will make sense to have a standard interface to the state/storage in 3id-connect now. Then that can be shared over a permissioned rpc layer or the same interface can just be directly exposed to an app on the same domain.

Yes I agree that would be useful, I'm not sure it's a requirement if the management app only takes care of flow 3 because it would be a specific implementation rather than a need for a generic interface.

> As we mentioned in past calls, the quickest/simplest path for this still would be to have this app on the same (3id-connect) domain. It would then have a shared library with 3id-connect for a few calls and a shared state/storage interface for the core data there now (ie dids, authsecrets, etc). Of course this comes with the security tradeoffs, which we can then mitigate in future iterations by moving parts to other domains. One proposal was just moving out all the providers for example (or entire app still). But either way with interfaces above( shared lib, state/storage), not much would change hopefully, just they would be over some rpc calls and relayed/permissioned as needed (depending on configuration)

Yes we always come down to the security vs UX trade-offs. I think part of the problem (at least for me) is understanding the scope of 3ID Connect being a "product" or a more "low-level" technical option among others?

Maybe the solution here could be to have a clear separation between 3ID Connect as a low-level technical solution (minimal UX constraints, maximal security) and "Self.ID Connect" as the product/high-level UX solution?
So all these UIs for managing accounts would be part of Self.ID, even the popup prompts we currently have in 3ID Connect, while 3ID Connect would store the data and provide RPC APIs for allowed domains.
Then ideally the only user interaction between the user and 3ID Connect would be a single prompt granting access to the data from the domain?
