### ISSUE TITLE
Write technical explainer for the 3ID DID Method

### ISSUE THREAD

**Issue by oed** [3box/3box#1320]

**Comment by dazuck** [comment]
@oed not sure the tone you intend here - pure technical walkthrough or more explainer -- but if the latter, including more of the "why" behind some decisions will make it a really good blog post to circulate at times too, as opposed to just docs to have for incoming. Not critical just input as you write.

**Comment by oed** [comment]
See PR here: https://github.com/ceramicnetwork/CIP/pull/79
