### ISSUE TITLE
Ceramic Data Recovery Playbook

### ISSUE THREAD

**Issue by zachferland** [3box/3box#1330]
Notion document that considers possible failures and includes a general strategy and plan to deal with any failures related to storage that require infra to be recovered from backups/replicas. Can also include plans/risks when changing parts of our infra related to our core storage layers. Should be simple with s3 though and a single point of core storage. 

Also briefly consider other parts, ie postgres for CAS.

**Comment by oed** [comment]
Might be a good idea to document this in a markdown file in the ceramic-infra repo so we don't lose it.
