### ISSUE TITLE
3ID Account State Store

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1338]
Interface to read/write state needed for 3id management library. State currently includes authsecrets, dids and caip-10 links. Later can consume different storage layers if required and/or be consumed over RPC layer. Also could be used in 3id-did-provider for permissions. 

- Define storage backend interface (async get/set/delete data)
- Create store frontend class (add DID, add account link, etc.)
- Create LocalStorage wrapper for storage backend
- Create in-memory wrapper for storage backend (for tests)

**Comment by zachferland** [comment]
Thinking now we can deprio this a stand alone module for now and #1339 (management lib) will cover all functionality necessary for both 3id-connect iframe and management app for first iteration (ie reads like didlist, linklist, etc without direct localstorage & (de)serialize). Then can revisit after first iteration of management lib.

**Comment by PaulLeCam** [comment]
Sounds good! As long as we start having a separation of concerns between the management lib and storage it's a good first step I think 👍
