### ISSUE TITLE
iFrame transport for JSON-RPC

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1340]
Communication between 3ID Connect, the apps using it and the management app must be done using the browsers' postMessage APIs.
We could create a generic transport mechanism along with https://github.com/ceramicnetwork/js-rpc-utils to provide a high-level RPC library used by these different libraries.

**Comment by zachferland** [comment]
Perfect, been wanting to rely more on js-rpc-utils for most of the places we are relying on postmessage (did provider relay, iframe control, authprovider, etc)
