### ISSUE TITLE
3ID Connect repository setup

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1342]
3idconnect.org will host both the current 3ID Connect iframe and management app, so we need to make sure deploying changes to either doesn't affect the other in expected ways.
To achieve this it probably makes sense to have the management app part of the same repository as 3ID Connect, with shared tests and deployment process. It should also make it easier to share UI components between the iframe and management app as needed.

Suggested approach:
- In a first stage, add an extra folder in 3ID Connect's repository to store the management app
- Management app and iframe should be built to the same folder, making sure the build process of one doesn't delete contents of the other
- Switch to shared build process and tests for the iframe and management app when possible
- Once the separation of 3ID Connect's APIs (between storage, management and connect libraries) is done, split them into individual packages and make 3ID Connect a monorepo

**Comment by zachferland** [comment]
yup this make sense to me, and the ordering 

maybe we just prioritize the first 3 for now, and we keep this story for moving management app, and ill create a another story for the release pipeline (paired with 3id-connect) 

unless moving to monorepo sooner than later really makes things easier?

**Comment by PaulLeCam** [comment]
Yes sounds good!
I don't think we need to worry about the monorepo/individual packages for now, I mostly wrote this last step as the end-goal but longer-term.
