### ISSUE TITLE
3ID Connect Management app in 3ID Connect repo

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1343]
- Opened by 3ID Connect
- Receives CAIP-10 account the main app is authenticated with (from query param? or message event?)
- Authenticate with provider chosen by user to get AuthProvider
- Create DID using AuthProvider with 3ID management lib
- Store created DID in 3ID Connect’s local storage
- Notify 3ID Connect back with created DID

**Comment by zachferland** [comment]
Is this for implementing core features in management app? 

May make sense to prioritize this flow first (being the most complex and making sure it works), but the other flows should still be included. 

1) user wants to link app authprovider caip10 to existing did. 3id-connect may be able to handle if only one other did. But list of dids would be management app. Management app would just allow user to select did, then use AuthProviderRelay and call createAuthAndLink(did) 

2) user after entering management app, user actually decides they just want to create new did with app authprovider caip10. Management app would then use AuthProviderRelay and call createAccount() 

3) user wants to link to did not currently in iframe. User selects provider/AuthProvider in management app. Management app then using that authProvider calls createAccount(), lastly its uses AuthProviderRelay to call createAuthAndLink(newly_created_did)

**Comment by PaulLeCam** [comment]
OK thanks for the details!
I think it makes more sense to implement the 3 flows then, so we can make sure the management lib and interactions with 3ID Connect work for in all these cases rather than trying to work on these in isolation? At least I found find it more efficient to work on the management app taking all these considerations into account at once.
