### ISSUE TITLE
Release js-ceramic (prod)

### ISSUE THREAD

**Issue by valmack** [3box/3box#1356]

**Comment by valmack** [comment]
This is pending @oed 's timestamp changes

**Comment by stbrody** [comment]
Done! https://github.com/ceramicnetwork/js-ceramic/commit/e5e8e92e1cb2da9623aba95507925185694b1638

**Comment by valmack** [comment]
@stbrody Prod release, not rc. I should have specified.

**Comment by stbrody** [comment]
Do we actually want to do a prod release this sprint?  I thought the plan was to wait until the tests are stable, the state refactor is finished, and the developer API updated

**Comment by valmack** [comment]
> Do we actually want to do a prod release this sprint? I thought the plan was to wait until the tests are stable, the state refactor is finished, and the developer API updated

@oed 

If we don't do a prod release infra options are:
1. move Clay off of prod and onto rc, proceed with metrics updates, data recovery updates, etc
2. wait until we release to prod before doing any updates

**Comment by oed** [comment]
Hm, I don't think it makes sense to use the RC on Clay. So either we wait or make a release early, or wait IMO.
