### ISSUE TITLE
Cannot add 3box

### ISSUE THREAD

**Issue by 0xTimepunk** [3box/3box#1369]
**Describe the bug**
Cannot do yarn add 3box, it seems the author of a dependency has deleted the repo?

![image](https://user-images.githubusercontent.com/45543880/112978059-c0059500-914e-11eb-8f2f-6f0657b5e855.png)

**To Reproduce**
yarn add 3box

Thanks

**Comment by oed** [comment]
Thanks for reporting @0xTimepunk We are investigating the issue.

Worth noting is that we are eventually going to stop maintaining 3box-js in favor of the [IDX sdk](https://idx.xyz).

**Comment by 0xTimepunk** [comment]
Sounds good.

Adding the 'next' release of 3box seems to solve the issue.
