### ISSUE TITLE
Pinning does not respect dag-jose

### ISSUE THREAD

**Issue by ukstv** [3box/3box#1406]
Current https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/store/pin-store.ts does not actually pin records linked to dag-jose.

**Comment by oed** [comment]
Why not? This seems extremely problematic!

**Comment by ukstv** [comment]
dag-jose was introduced slightly after pinning was done. Problematic. That's why p1.

**Comment by oed** [comment]
I would even put this to `p0` this might be why we have been seeing some issues.
