### ISSUE TITLE
Ceramic Playground Updates - Ceramic Project

### ISSUE THREAD

**Issue by Sterahi** [3box/3box#1429]
Convert the quickstart of Ceramic's HTTP Client or Core Client into an easily parsable package.

**References**
Core: https://developers.ceramic.network/build/javascript/core/
HTTP: https://developers.ceramic.network/build/javascript/http/

Configure a simple file to connect to show the most simple connections to Ceramic node (let's use the testnet node for it). This should include connecting to IPFS & using dag-jose & using DID Resolvers. It'd be nice to have a simple auth example.

**Comment by oed** [comment]
Can you elaborate a bit on what this means and what's included?
I suppose this is for the web-playground updates? Next time you can add the ticket directly on the web-playground repo :)

**Comment by michaelsena** [comment]
Easiest to start with HTTP Client
