### ISSUE TITLE
Reserach how to scale the pinning-server

### ISSUE THREAD

**Issue by oed** [3box/3box#217]
Currently we are using an integrated ipfs + orbitdb node for pinning, this doesn't scale that well.
Data is stored in the ipfs node, orbitdb also stores some data in the `./orbitdb` folder. There are some paths to investigate:

* Use one ipfs node and multiple orbitdb nodes that connect to it. <br/>This means that all 3box-js clients would connect to the same ipfs node (same ipfs multiaddr) but their orbitdb metadata would be saved on different nodes.

* Use multiple nodes that have both ipfs & orbitdb <br/> This means that each 3box-js node would need to know which node to connect to in order to get their data replicated.

* A combination of above with **n** ipfs nodes & **m** orbitdb nodes, where **n** < **m** <br/> I'm not sure this has any advantage over the first two alternatives.

The result of this research should be to compare the pros/cons of these and any additional setups for pinning, and suggest a way of implementing atleast one of them.

**Comment by oed** [comment]
@c-castillo is this part of what you are doing currently?

**Comment by c-castillo** [comment]
@oed yes, it's a good summary

**Comment by oed** [comment]
@c-castillo ok, should we put this to in progress then?
So once you are done with the research you can outline how it will be implemented so that everyone else is aware of how it works 🙂

**Comment by oed** [comment]
@c-castillo I was thinking about this the other day. I liked your idea of sharding based on the modulo on the hash of your odb-address. I think we can extend it like this:
calculate your shard id by: `sid = h(odb-addr) % n` where n is number of shards. 
When you send your address to the pinning server use pubsub room with name: `3box shard <sid>`

Now we can have pinning servers that listen to different pubsub rooms (one server might listen to multiple).
