### ISSUE TITLE
Research: use ERC712 for consent signatures

### ISSUE THREAD

**Issue by oed** [3box/3box#218]
Right now we are using `personal_sign` for the openBox signature and the linkConsent signature. We might want to switch to ERC712 before we release 1.0.0

The output of this research should be a specification for how to implement ERC712 on the `address-server` and in `3box-js`

**Comment by ajunge** [comment]
Why ERC-712?

**Comment by ajunge** [comment]
But the signature in 3box is not being verified on-chain.

**Comment by oed** [comment]
True, but we can be more shore that this will always be available. But yeah, maybe this doesn't matter that much. It will make us compatible with uport though, but that's not really a prio in it's own sake.

**Comment by oed** [comment]
Just tried with a bunch of web3 wallets on mobile. It's not available on the following:
* Vault
* Trust wallet
* Coinbase Wallet
* imToken
* Status.im
