### ISSUE TITLE
Stress test the secondary environment and not myself

### ISSUE THREAD

**Issue by c-castillo** [3box/3box#249]

**Comment by oed** [comment]
Things we should be testing: 
* A lot of nodes calling openBox() at once. All of them should have at least 20 entries in their public and private store respectively. We can try with 10, then 100, then 1000?
* A lot of nodes adding data at once. All of them should add 30 entries to their public stores at the same time. Let's try with 10, 100, then 1000 here as well.

These two seems like the most important aspects to test.

**Comment by c-castillo** [comment]
Agree with the points above @oed
