### ISSUE TITLE
Update git flow branch naming convention

### ISSUE THREAD

**Issue by oed** [3box/3box#264]

**Comment by jjperezaguinaga** [comment]
@oed What branching convention you guys are using? We most likely going to move our project workflow to ZenHub as well, so wanted to check how that affects branching setup. Also, how's your satisfaction with ZenHub as a whole?

**Comment by oed** [comment]
You can have a look at our [best practices](https://github.com/uport-project/3box/blob/master/REPO-BEST-PRACTICES.md), but this story is for updating that very document. Will still be similar though. 

Zenhub doesn't really affect the branching in your repos. Really like zenhub as a system! Keeps all product management close to the source :)

**Comment by jjperezaguinaga** [comment]
@oed Thank you for sharing your insights ☺️ we will be migrating to PM in Github only by January, so gathering some info of different tools. Did you try something else other than ZenHub?
