### ISSUE TITLE
Apply for EF Grant

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#306]

**Comment by dazuck** [comment]
@michaelsena do you have any idea when the due date for Wave V is? can't find that info. Can reach out to them if not - we should submit soon but i think probably good to wait a couple weeks if possible given other stuff afoot

**Comment by michaelsena** [comment]
I connected with Sina from EF Research on Telegram and he offered to walk us through the grant application process. Will open a thread with you both in the next few days. @dazuck
