### ISSUE TITLE
"Getting started with 3Box" feature 

### ISSUE THREAD

**Issue by dazuck** [3box/3box#354]
Publish a 'getting started with 3Box' post for Kauri's collection. Can also do one for creating a profile but we probably can hold off on that for now. 
https://beta.kauri.io/collection/5bef33b16b97660001fe6392/quick-start-web3.0-series

**Comment by c-castillo** [comment]
Strongly agree with this feature as well.

**Comment by dazuck** [comment]
https://beta.kauri.io/article/204bee70b23549f2acdc873d265d98f8/v1
