### ISSUE TITLE
Set up notion for effective tracking & conversion of partners

### ISSUE THREAD

**Issue by dazuck** [3box/3box#364]
As a 3Box core team member, i can see our list of relationships + projects in Notion, with an easy way to see who are targets are, what there status is, what their key needs are, and what the most recent activity with them has been.

**Comment by dazuck** [comment]
@michaelsena if we're going in on notion as a team might as well invest in this, i think. Lmk if you have any doubts before we start the sprint though

**Comment by michaelsena** [comment]
I took a look today @dazuck it looks good. I also added another column for use cases - and created two as starters: "social profiles" is one option, and "PKI" is another option. I added these to the Airswap row
