### ISSUE TITLE
Post EthSingapore bounties 

### ISSUE THREAD

**Issue by dazuck** [3box/3box#384]

**Comment by dazuck** [comment]
@michaelsena do we know what these are yet? Going to come pretty quick given timezone difference

**Comment by michaelsena** [comment]
We don't know yet but good callout, any ideas?

**Comment by dazuck** [comment]
@michaelsena started a list here. I feel like there are a lot, will keep populating and we can keep that as a running list. https://www.notion.so/threebox/Bounty-Random-Ideas-d27a002c8fd149a183ab9e4b4e9f9802

**Comment by michaelsena** [comment]
Here are the Bounties I posted:
https://explorer.bounties.network/bounty/1923
https://github.com/gitcoinco/web/issues/3121

We still need to ping the Gitcoin team to see what we need to do to fund the issue that integrates 3box with the Gitcoin avatar builder. @dazuck you said you spoke with Kevin?
