### ISSUE TITLE
Publish "3box team culture and how we work" 

### ISSUE THREAD

**Issue by dazuck** [3box/3box#385]
Goal of this is to make candidates really clear and excited about how we work.

**Comment by michaelsena** [comment]
@dazuck where does this stand or should we move this to backlog until a few more sprints when we can spend time on it?

**Comment by dazuck** [comment]
@michaelsena was about to move it to "review" as it's ready for content review here - https://www.notion.so/threebox/3Box-Culture-A-Team-Community-Company-bbfdf15c76f44c158728f59bc82a4ea3

I think it should stay there til you have time to edit then I will publish, but shouldn't be marked "Sprint 12" if it doesn't meet priority requirement to get it across the line.

**Comment by michaelsena** [comment]
@dazuck done w/ copy revisions - now need to add visuals:
* 1 photo of the team
* 1 photo of the purpose board
* 1 designed image file for the banner photo

**Comment by michaelsena** [comment]
Added images to the [Notion draft](https://www.notion.so/threebox/3Box-Culture-A-Team-Community-and-Company-bbfdf15c76f44c158728f59bc82a4ea3). Moving this to Staging pending your final review @dazuck. Let's aim to publish this tomorrow morning
