### ISSUE TITLE
Research better private store implementation

### ISSUE THREAD

**Issue by oed** [3box/3box#398]
Right now the private store requires the user to know the keys to get data from the private store. This is not optimal and it would be good if both the key and value where encrypted. This likely requires us to implement a custom orbitdb store, but let's research.

We likely don't want to update the existing private store at this point. However all of the private spaces can use this implementation, and if it works well we can create a migration plan for the general private store.

**Comment by zachferland** [comment]
I think the best solution is to implement payload en(de)cryption in ipfs-log. At the log layer for kv store this includes en(de)crypting both the key/value. Since the identity-provider was added, its much easier to implement now by just adding encrypt, decrypt functions to the identity provider and then implementing in ipfs-log. Then on our end we only have to pass an identity provider with an enc key for all key/value to be abstractly en(de)crypted at the lower layer.

**Comment by zachferland** [comment]
This will also give en(de)cryption for other stores as well, besides kv stores, if that is useful in the future.

**Comment by oed** [comment]
@zachferland I was thinking the same thing. Basically some way of passing encrypt/decrypt functions to the ipfs-log. I'm wondering though, would this limit the feature to only be used by dbs owned by one key? How would you do encryption with multiple users, especially when adding new users at a later point?
Also The identity-provider stuff is not merged in orbit-db yet right?

**Comment by zachferland** [comment]
I don't think it would limit it, at least at first thought, unless I'm missing something. At this layer, i think all that matters is there a key or not at this layer to en(de)crypt, and its not really opinionated about anything else. I imagine for other schemes, management would be layers up, orbitdb likely, or 3box. Do you have any other thoughts/examples about multi-party encryption that could effect it? plus probably fine for some time, even orbitdb is also still a bit of a ways out from figuring out access-control well.

The identity provider is in ipfs-log and orbit-db-store, then in orbit-db there is the keystore, which a identity-provider is then created from that. So appears to be available through out.

**Comment by oed** [comment]
Ok, so let's say I have an encryption key E that is used to encrypt store A. Then I would need an ACL external to A where I can publish E encrypted to your public key in order to give you access to A. I think that makes sense, but it seems a bit further out on orbitdb's roadmap? Is there anything easier that we could do in the mean time, or do you think it would be a fairly easy add to orbitdb?

**Comment by michaelsena** [comment]
We still want to make a writeup of the OrbitDB way. Bumping back to backlog until @zachferland returns.
