### ISSUE TITLE
Document analytics platform

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#405]
# Tasks
* Produce end-to-end system reference documentation in Notion for internal use. This will help others engage with the analytics platform if needed, or how to modify an existing metric.

# Topics
what are we measuring?
how are we measuring it?
If we create new functionality in the lib, how do we add it to metrics platform?
How can we query the data?
...

**Comment by michaelsena** [comment]
@oed and @michaelsena to review

**Comment by oed** [comment]
Closing this as it's finished.
