### ISSUE TITLE
Draft version of values for discussion with team

### ISSUE THREAD

**Issue by dazuck** [3box/3box#418]
Synthesize the discussions on retreat into a first set of team values.

**Comment by dazuck** [comment]
@zachferland @c-castillo @christianlundkvist check out https://www.notion.so/threebox/Values-a3ac416be1a34d90909c024e7541ecbe when you get a chance. this is a draft of team values coming out of retreat. We'd love to do a team meeting in a week or so to finalize them as a group.

**Comment by c-castillo** [comment]
@dazuck looks good to me
