### ISSUE TITLE
Clean up 3box repo

### ISSUE THREAD

**Issue by oed** [3box/3box#420]
Make sure files are structured and up to date

**Comment by michaelsena** [comment]
@oed giving this back to you for next sprint because you have a clear idea how you want the files structured

**Comment by michaelsena** [comment]
@oed I merged the new 3Box readme, so this is avail for you to take on whenever. Just comment in here when you do it, because it will likely break a few image links that exist in the repo files and link elsewhere in readmes

**Comment by michaelsena** [comment]
@oed just went through. Thanks for making those updates. I added a few very small edits... I know I'm crazy 😝. After you fix those this should be good to merge.
