### ISSUE TITLE
Define proof for linking a contract wallet

### ISSUE THREAD

**Issue by oed** [3box/3box#421]
Should be done using [EIP1271](https://github.com/ethereum/EIPs/issues/1271). This story should define how and where to store the proof.

**Comment by oed** [comment]
https://github.com/3box/3box/issues/251#issuecomment-434838047

**Comment by oed** [comment]
Ready for review here: https://www.notion.so/threebox/3IP-Contract-wallet-support-aa26fe69f4df45b69e39ab4a24c4967b

**Comment by michaelsena** [comment]
@oed pulling this story back into upcoming sprint backlog, but can you update the title and break it into multiple stories if needed [i.e. 1) Link 3Box account to a contract, and 2) Add authentication methods to a 3Box account]

**Comment by oed** [comment]
Split them up. The other ticket can be found here: https://github.com/3box/3box/issues/586

**Comment by michaelsena** [comment]
Looks good
