### ISSUE TITLE
Spec metrics for our infrastructure services

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#422]
Define a set of infrastructure metrics it makes sense to display.

We will get everything from cloudwatch regardless.

Top of mind metrics:

- [ ] Are services operating currently?

- [ ] Disc space used by pinning-nodes

- [ ] CPU requests

- [ ] ...

**Comment by michaelsena** [comment]
@dazuck and @c-castillo have we specced these? @c-castillo this should have likely been done before you started building so we could have been aligned which were the MVP metrics. This would have indicated timeseries v count. Should we close this now or what should we do here?

**Comment by c-castillo** [comment]
@michaelsena carrying over to the upcoming sprint is good. Also, create the building story associated with the spec that will be produced here.

**Comment by c-castillo** [comment]
Thanks @michaelsena for the clarifying question.

After the spec is done, and it specifies what and how kpis should be measured, the story should reflect the effort needed to generate the data that is going to be sent to the warehouse through the pipeline).

Another story should be created to generate those particular dashboards according to the spec.
