### ISSUE TITLE
Implement twitter verification service

### ISSUE THREAD

**Issue by oed** [3box/3box#444]
Implement a serverless function that can verify twitter accounts and issue a claim. See #440 and [this spec](https://www.notion.so/threebox/Twitter-verification-with-serverless-1d7d038287004c4cb77bf1c87ea95838)

**Comment by jjperezaguinaga** [comment]
Might be useless to you guys, but Keybase created their proof system like [this](https://github.com/keybase/proofs/blob/master/src/scrapers/twitter.iced), and you could inspire yourselves in [Blockstack](https://github.com/blockstack/blockstack-proofs-py) as well. I unfortunately can't see the spec so none of this might help you 😞

**Comment by oed** [comment]
@jjperezaguinaga not sure why Keybase and Blockstack are parsing the html of the websites when they can just do OAuth. Their code is running on the backend anyway.
