### ISSUE TITLE
Document release settings for our services

### ISSUE THREAD

**Issue by oed** [3box/3box#451]
We should setup and document how our services are deployed. Currently this is not setup but we'd want something like this:

## 3box-verifications
* master -> verifications.3box.io
* develop -> verifications-dev.3box.io

### ipfs node
* master -> ipfs.3box.io
* develop -> ipfs-dev.3box.io
### cache service
* master -> api.3box.io/cache/
* develop -> api-dev.3box.io/cache/

## 3box-graphql
* master -> api.3box.io/graph/
* develop -> api-dev.3box.io/graph/

## 3box-dapp
* master -> 3box.io
* develop -> develop.3box.io

We should also think about similar setups for:
* 3box-js-iframe

@michaelsena how is 3box-dapp setup?

**Comment by oed** [comment]
ty @michaelsena! Can also provide some descriptions for what purpose the beta and develop branch serves respectively?

**Comment by michaelsena** [comment]
@oed updated my previous comments with better descriptions
