### ISSUE TITLE
Restart pinning node if memory limit has been reached

### ISSUE THREAD

**Issue by c-castillo** [3box/3box#468]
Based on @zachferland 's restart of the pinning server due to eating almost all the memory available.

pm2 already supports that feature.

https://pm2.io/doc/en/runtime/features/memory-limit/

**Comment by oed** [comment]
I'm wondering if the timeout to close DBs feature isn't working? Or maybe there is a memory leak in orbitdb?
Any other thoughts on what could be causing this @zachferland?

**Comment by zachferland** [comment]
I actually don't think the number of open non-active dbs matter to much, unless orbitdb/ipfs is doing some other stuff because web sockets are so cheap to keep open. More concerning is we were hitting 100% cpu, would be less concerned about memory alone if this wasn't happening, but must be related.  I think something is up with event listeners and that is registering 10s per open db, so 1000s overall. But need to get some better output tests.

But yeah if many events listeners be registered, maybe close db doesn't work in the sense that those events are not be unregistered. But still the original issue is there should not be that many

**Comment by oed** [comment]
Ok, thanks for the clarification!

**Comment by zachferland** [comment]
so there is this error, but the part about closing the dbs only logs on start, so many trying to close dbs that are not open or don't exist. The part about event emitters  has been going on for quite some time, and not only at start, which may definitely be part of the problem.

```
0|node     |     at EventEmitter.openDBs.(anonymous function).db.events.on (/home/ec2-user/3box-pinning-server/src/pinning.js:84:9)
0|node     |     at emitTwo (events.js:126:13)
0|node     |     at EventEmitter.emit (events.js:214:7)
0|node     |     at FeedStore.load (/home/ec2-user/3box-pinning-server/node_modules/orbit-db-store/src/Store.js:219:17)
0|node     | (node:1900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 226)
0|node     | (node:1900) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
0|node     |     at Object.keys.map (/home/ec2-user/3box-pinning-server/src/pinning.js:43:18)
0|node     |     at Array.map (<anonymous>)
0|node     |     at Pinning.checkAndCloseDBs (/home/ec2-user/3box-pinning-server/src/pinning.js:39:31)
0|node     |     at ontimeout (timers.js:498:11)
0|node     |     at tryOnTimeout (timers.js:323:5)
0|node     |     at Timer.listOnTimeout (timers.js:290:5)
0|node     | (node:1900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 227)
0|node     | (node:1900) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit
0|node     | (node:1900) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```
