### ISSUE TITLE
Verify email domain in Amazon SES

### ISSUE THREAD

**Issue by c-castillo** [3box/3box#469]
*Email address is not verified*. The following identities failed the check in region region: identity1, identity2, identity3—You are trying to send email from an email address or domain that you have not verified with Amazon SES. This error could apply to the "From", "Source", "Sender", or "Return-Path" address. If your account is still in the Amazon SES sandbox, you also must verify every recipient email address except for the recipients provided by the Amazon SES mailbox simulator. If Amazon SES is not able to show all of the failed identities, the error message ends with an ellipsis.
Note
Amazon SES has endpoints in multiple AWS Regions, and email address verification status is separate for each AWS Region. You must complete the verification process for each sender in the AWS Region(s) you want to use.

**Comment by c-castillo** [comment]
Escalated the case opening a new one with higher severity

**Comment by michaelsena** [comment]
Any news @c-castillo? Assuming if we don't get this pushed through today, we'll hit a delay with the weekend? Can I help if stuck?

**Comment by c-castillo** [comment]
@michaelsena 

There's no phone number but you can open a new case and select being contacted on the phone. Some details:

Account: 967314784947
Case number: 5742985451

If this is not solved during the weekend, I'll start integrating mailchimp api (since we already have an account) into the service an drop aws.

**Comment by c-castillo** [comment]
@michaelsena It got solved. Closing this now
