### ISSUE TITLE
Gather requirements for simplified threads spec

### ISSUE THREAD

**Issue by oed** [3box/3box#498]
The output of this story should be a list of requirements for the simplified threads spec.

**Comment by michaelsena** [comment]
@oed any idea how moderation would work on the first version of threads: public comments? For this to be implementable by folks in production, some have expressed some ability to moderate content in threads. Is the easiest first version of moderation that the owner of the OrbitDB store (i.e. the article poster) is able to remove comments?

Shadowbanning users was also expressed as a requirement however, that seems like something we could add on later. However I do believe MVM (minimum viable moderation) would be required even in v1.

**Comment by oed** [comment]
If we want to have the ability of a single moderator to remove comments we need to use access controllers of orbitdb v0.20.0, which is still unreleased but expected soon. I don't think it actually makes sense to start working on threads before that. 

Shadowbanning is tricky in a decentralized environment, since users could always check if they are shadowbanned. There still could be somethink *like* shadowbanning though.

**Comment by michaelsena** [comment]
When is soon to the Orbit team? Like next sprint soon, a month, a quarter?

If too long, then maybe we can still implement V1 with no moderation to get people playing around with out threads feature, and then add it in quickly in v2?
@oed

**Comment by michaelsena** [comment]
@oed do you think you can draft up your thoughts for a very MVP version of this. Feel like we're getting pretty behind on this. What would we need to build to migrate the 'status' in user's 3Box profiles into a thread? If the user owns the thread, can they "self-moderate" the comments, aka, delete previous statuses?

I'm sure there's some complexity and API work required to enable another store type, so this alone might make for a good MVP...
