### ISSUE TITLE
Create sequence diagrams for crypto flows

### ISSUE THREAD

**Issue by oed** [3box/3box#500]
This will make things clearer and simpler to understand. We can use plantUML: http://plantuml.com/sequence-diagram

**Comment by oed** [comment]
Ready for review here: https://www.notion.so/threebox/Onboarding-2-5-spec-d11470694816404196a772b55d5c56e4

**Comment by michaelsena** [comment]
@oed I reviewed the full spec and looks great. Thanks for all the detail. Can likely move these spec stories to closed now

**Comment by oed** [comment]
Thanks @michaelsena, I'd like to wait a bit though. Found some things that will likely require some small changes. Will give an update at standup.
