### ISSUE TITLE
Refresh project outreach priorities

### ISSUE THREAD

**Issue by dazuck** [3box/3box#503]
Update project tracker in Notion
Identify the right 2 week goals

**Comment by mattlockyer** [comment]
Refresh project priorities

Refresh process

**Comment by mattlockyer** [comment]
Refreshed project tracker columns:
https://www.notion.so/threebox/c7d4c5c1ce1a4eb7ba13ee8c2751b289?v=9ec3419a2e724ac78478bbbf79e5e829

**Comment by mattlockyer** [comment]
Added Goals and Priorities page to MARKET to steer the discussion
https://www.notion.so/threebox/Goals-and-Priorities-e033e69e17e84f8d8ed1028ee5250220

**Comment by mattlockyer** [comment]
Added a TODO property and view to the Project Tracker
https://www.notion.so/threebox/c7d4c5c1ce1a4eb7ba13ee8c2751b289?v=136e28b6fd1545968f3a78c4a0f68aa9
