### ISSUE TITLE
Implement an orbitdb cache that can be shared across nodes

### ISSUE THREAD

**Issue by zachferland** [3box/3box#507]
Part of this story is decide which type of shared store is best. Then implementation. We have done something similar for the iframe, the interfaces is rather minimal, and is a level down compliant store, so we should be able to find a existing library for most stores.

**Comment by zachferland** [comment]
First minimal implementation here - https://github.com/3box/orbit-db-cache-redis. Leveldown compliant redis store for level up was very out of data, this is just simple orbitdb cache interface wrapping a redis client. 

Not concerned about concurrent writes. I think LWW (last-writer-wins) is mostly sufficient, but there could be some issues since local/remote head is a list of objs, have see how these are updated/changed, if they are read, appended to, then update then there could be an issue. But mostly not concerned since there is good medium term solutions which include, we could implement different locking mechanisms (some opts provided) at redis layer (or other dbs), also can do things like implement a crdt for these key vals to get eventual consistency (which is sufficient here) (think redis clusters already do something like this)

**Comment by oed** [comment]
> some issues since local/remote head is a list of objs

So basically if the head is currently `A`, **and** `B`, then it get overwritten by `C` but `C` only references `A`?

Could maybe be a problem if two apps use the same store at the same time?

**Comment by zachferland** [comment]
yup was saying it could be problem, but to clarify further -  yeah, or just adding to the list, node 1 reads heads[a, b] then adds c and writes [a, b ,c], while at the same time node 2 reads heads[a, b] then adds d and writes [a, b, d]. Overwriting  [a, b ,c], then state is  [a, b, d], instead of [a, b ,c, d] or some other changed pointers.

I still need to dig one step deep to determine exactly whats up, I don't quite follow why there is always so many heads tracked, I thought most of the time it would end up being 1 head (in those cases LWW should work). 

Right now when do you imagine two apps could use the same store at the same time? or that they would both have log changes at the same time? This would also have to happened with in same sec/ms, which at our current throughput would be excedingly small. Also data loss would be minimal, and even if concurrent writes, it would in most chances get the remote heads (from app) when opened again later, and updated correctly) Seem like non issue right now, but worth noting for the future, and not concerned since plenty of possible good solutions in the future.

But at the same time, yeah we need to figure out what we know for sure and be able to simulate everything to confirm, so that we are chasing insane async bugs in the future.

**Comment by oed** [comment]
> Right now when do you imagine two apps could use the same store at the same time? or that they would both have log changes at the same time?

Yeah, agree that it's mostly likely not a big concern right now. I guess the main event this might happen in is when two dapps updates the main profile at the same time. Given the direction we are moving in (using spaces/dapp specific storage) it seems like this will be less of an issue in the future.

**Comment by zachferland** [comment]
Conversation above has become larger concern, one because with threads, we should still stick to the assumption that multiple nodes may open the same the store, and two some scenarios have not been addressed. The concern is not so much concurrent writes and corrupted state at the moment (although part of it), but more that if two are writing around the same time, even if updates end up in store, the other node might not know that there was an update. Also a lot of this is still dependent on how it is implemented in orbitdb, if orbit always looks to the cache before return values then this still mostly works, if it only reads the cache on open, then this definitely doesnt work. Also depends on how the val is updated, as described above.  Closing this story since this was for implementation, creating new story to address questions above before we run multiple nodes.
