### ISSUE TITLE
Implement  profile cache/api as new serverless service. 

### ISSUE THREAD

**Issue by zachferland** [3box/3box#510]
Review details in notion.

**Comment by zachferland** [comment]
This will have to be redefined/scoped when we pick it up again. By then it will also include threads, and the recent spaces api. Can also be separated into layers. A function to read a store from S3, then all the functions which actually server as the api.

**Comment by oed** [comment]
@zachferland Do we think we should put effort into doing it sprint 16 or hold of for now?

**Comment by zachferland** [comment]
Nope, on hold,  removed milestone before, just didn't show here

**Comment by oed** [comment]
Making this into an epic
