### ISSUE TITLE
Document 3Box On-Boarding

### ISSUE THREAD

**Issue by mattlockyer** [3box/3box#518]
Will be in Notion

**Comment by mattlockyer** [comment]
https://www.notion.so/threebox/Onboarding-6ffb46d56bec4b1fae0d0ae787bc6a9c

**Comment by mattlockyer** [comment]
Asking for a bit of feedback on this doc.

Purpose: mainly to provide a primer on the tools and process. We have an amazing process but someone might need a way to dive right in and this should help!

**Comment by oed** [comment]
Looks great, thanks @mattlockyer! I added some comments.

**Comment by dazuck** [comment]
@mattlockyer thanks for this. Let's close and revisit for the next hire!
