### ISSUE TITLE
[Requirements] Public Moderated Threads

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#558]
The result of this story should be a set of requirements for the moderated threads.

**Comment by oed** [comment]
General requirements can be found here: https://www.notion.so/threebox/Public-Moderated-Threads-a806cbe8c449415db61e081d620c7331

The parts we aim to implement this sprint:

## 1. Moderated, open

This type of thread is open for anyone to post in, and there is a set of moderators.

### Any users can

- Post in the thread
- Remove their own comments

### Moderators can

- Post in the thread
- Remove their own comments
- Remove users comments
- Not remove other moderators comments
- Add new moderators

**Comment by oed** [comment]
@michaelsena @zachferland Please have a look over the notion doc linked above
