### ISSUE TITLE
Migrate to new orbitdb version

### ISSUE THREAD

**Issue by oed** [3box/3box#570]
This is a bit of an exploratory story. First as an experiment we should migrate our current system to be compatible with the new orbitdb-identity-provider, without the use of 3ID. 

We need to make sure that this works with spaces as well.

This story will likely inform the design of 3ID.

**Comment by zachferland** [comment]
hmmm how it thought it works changed a bit again, i thought the access controllers were based on the id (from the identity provider) not the pubkey of the orbitdb keypair created. Not much of blocker still, can create another access controller, but not sure why this isnt the default with the new identity providers.

**Comment by zachferland** [comment]
other notes 

- ipfs.files.add changed to ipfs.add (ipfs upgrade)
- db.all() -> ....

**Comment by zachferland** [comment]
db.all() -> db.all    (was just changed to a getter)

**Comment by zachferland** [comment]
- Pulled in @oed orbitdb PRs
-  some changes above
- passed in Orbit identity provider that maps to our current model (some parts just mocked right now)
- modified ipfs Access controller to look for identity.id in write access, if identity in entry, and to verify identity

With those changes i was able to open existing stores and add entries to them, same for spaces. That seems to be the bulk of what is needed for the migration so far.

**Comment by oed** [comment]
Oh, that's strange about the access controller. Looks like the [orbitdb-ac](https://github.com/orbitdb/orbit-db-access-controllers/blob/master/src/orbitdb-access-controller.js) does the same right?

**Comment by zachferland** [comment]
https://github.com/3box/3box-js/pull/418

**Comment by zachferland** [comment]
@oed anything else we want to follow up on or write down to be able to close this?

**Comment by oed** [comment]
I think we are good @zachferland Will follow up on your code tomorrow

**Comment by zachferland** [comment]
Anything else that comes up, will be found here - https://github.com/3box/3box-js/pull/418 going forward
