### ISSUE TITLE
Create AsyncStorage IPFS Repo 

### ISSUE THREAD

**Issue by zachferland** [3box/3box#597]
Created IPFS repo backed by asyncstorage for react native. Can use almost all same code just pass in abstract-levedown compliant store. https://github.com/tradle/asyncstorage-down. 

Before starting, should still confirm if this is necessary. Check what others are have done for running js ipfs in react native. There are indexeddb shims, should in theory work, but haven't. Also depends what storage layers those shims are using. 

Could be performance differences as well.

**Comment by kuhnchris** [comment]
One other way I found is to have an intermediate server to connect to IPFS:
https://github.com/samie820/IPFS-React-Native/blob/master/src/services/FileUpload.js

**Comment by kuhnchris** [comment]
Also, there seems to be a textileio version, but that one also doesn't use native jsipfs: 
https://github.com/textileio/react-native-boilerplate

**Comment by oed** [comment]
The intermediate server wouldn't really work since we need an instance of ipfs. Using the textile ipfs version would be cool, but we still need to use orbitdb which is in js.

**Comment by michaelsena** [comment]
closing, found another solve
