### ISSUE TITLE
Get 3Box.js to work in React Native

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#607]

**Comment by mirshko** [comment]
Heya! 

I'm working on a new little project and I was taking a look at the identity-wallet SDK, it seems its quite limited in terms of having a user setting data, or uploading a profile picture or something if you don't have a web-app pairing at the moment? Am I correct here? 

Whats the status of enabling the 3box SDK on React Native, my goal is to have, username, profile picture, and other data all editable on the app frontend with no pairing to a web app.

**Comment by tesla809** [comment]
I am inquiring the same. 

Would it be possible to use 3box with Textile's ThreadDB? 
It seems that ThreadDB but works with React Native, but is missing role-based permissions.

Is there a way to integrate 3Box's Decentralized ID with ThreadDB @michaelsena ?
