### ISSUE TITLE
Docs site MVP

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#626]
This site will live at docs.3box.io

**Comment by kuhnchris** [comment]
any reason to not generate them? (I assume it's the API docs, right?)
Then you'd use something like readthedocs and point it there, no? 
Else someone has to keep updating this...

**Comment by michaelsena** [comment]
Yup, will use a generator like Readthedocs or something, but will also have some supporting content around just the core API stuff. We'd need to structure the content in the appropriate way.
