### ISSUE TITLE
Full Suave integration spec

### ISSUE THREAD

**Issue by oed** [3box/3box#630]
Finalize the two options we've been working on and give a recommendation.

**Comment by michaelsena** [comment]
@oed when do you think it's realistic that we could have a one-pager back to them that outlines the integration?

**Comment by oed** [comment]
Wednessday or Thursday probably.

**Comment by michaelsena** [comment]
Even just for the one-page summary? They wanted to have a follow up meeting as early as next Thursday, and I assume that getting them something on Wed or Thurs will delay that. @oed

**Comment by oed** [comment]
I would say so, atleast to be confident that we'll be able to release updated threads in time on Tuesday. The one-pager needs quite a bit of work since what has been done so far for Suave had some different underlying assumption about the nature of the integrations. We can aim for having it ready on Wednesday though.

**Comment by michaelsena** [comment]
Thanks @oed - I made comments in the doc. Flow makes sense, my only feedback was around potentially updating method names to clarify language which might improve the developer experience for n00bs like me :)

**Comment by michaelsena** [comment]
@michaelsena to send to team for review.
