### ISSUE TITLE
E-Mail verification doesn't work on 3box.io

### ISSUE THREAD

**Issue by andreystarkov** [3box/3box#657]
I got this:

![](https://i.imgur.com/X46nnAH.jpg)

**Comment by oed** [comment]
Thanks for reporting @andreystarkov! We'll look into it.

**Comment by michaelsena** [comment]
@zachferland I know we had other email verification failures and you had fixed it. Seems some are reappearing again. Are they related? Wondering if we need to take a deeper look at what's going on here.

**Comment by zachferland** [comment]
@michaelsena last fix was not a permanent fix, current implementation is a bit unstable, likely the same issue, if so, will be able to fix tmrrw, eventually need to move the code store to another resource

**Comment by zachferland** [comment]
Making two medium term fixes 

- log status codes/requests to see failures 
- add short section on infra for this services and how to restart and collect logs
