### ISSUE TITLE
Implement charts we can with current pipeline

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#663]
Danny creates charts based on easy to create KPI goals

From here (not ones with red boxes) - https://docs.google.com/presentation/d/1j241zsxHom-gRDC2eHHngJ3HLlnTaGqeZPCSq8x3fMc/edit#slide=id.p

**Comment by michaelsena** [comment]
@dazuck or @zachferland mind listing our here the charts we can create with the pipeline ZF is currently setting up? The ones we cannot easily implement, I will create another placeholder story to spec those.

**Comment by dazuck** [comment]
@michaelsena i think we'll actually need to finalize this list tomorrow, unfortunately, as it should be the subset of the KPIs + team goals we arrive on after the board meeting. 

@zachferland it would be great if you can look at that notion doc before tomorrow (KPI section) to see the hypothesis raise any questions, though.
