### ISSUE TITLE
3Box.io: Github verification doesn't work

### ISSUE THREAD

**Issue by andreystarkov** [3box/3box#667]
I created a gist, then pressed verify button.
Got this:

![](https://i.imgur.com/0EB5XL8.png)

**Comment by oed** [comment]
Hey @andreystarkov thanks for reporting! In what format did you put your github handle in the input field? We are working on making it more robust, but right now I think you need to put it in without the @. 

cc @oznekenzo

**Comment by oznekenzo** [comment]
@andreystarkov did you make the gist file public in your github profile?

**Comment by andreystarkov** [comment]
@oznekenzo @oed 
i just copied link to my profile like https://github.com/andreystarkov and pasted at Github input field.
Your form expected that i will enter plain github username, but i missed caption over the field about format.  So you need some kind of validation there. Link parser on paste, maybe.

**Comment by oznekenzo** [comment]
Yes, apologies about that @andreystarkov.  We've gotten this mistake several times so we are addressing it in our next sprint.  Thank you for bringing this to our attention
