### ISSUE TITLE
3Box.io: Quota exceeded error

### ISSUE THREAD

**Issue by andreystarkov** [3box/3box#668]
I pressed sign in button, after metamask confirmation i got this:

![](https://i.imgur.com/yIq5BQY.png)

![](https://i.imgur.com/CGyEaCr.png)

I refreshed the page and it fired again.
After 3rd refresh its disappeared.

I don't know what was that, but maybe it will be useful.

**Comment by oed** [comment]
Interesting, haven't seen this before. Do you have any idea of what it could be @oznekenzo?

**Comment by oznekenzo** [comment]
No, have never seen this error...anything look familiar to you in the error stack @oed ?
