### ISSUE TITLE
Design discussion app for dappcon workshop

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#669]

**Comment by michaelsena** [comment]
First pass at something, but thinking something along these lines. @oed thoughts? If you think something like this is doable, I will continue to design the few other things it needs, such as logic for adding members to a members-only topic, flow for creating a new topic, etc.

![3chan mock v1](https://user-images.githubusercontent.com/5216274/61259114-c8355b00-a746-11e9-9591-2a7f24893cd8.png)

**Comment by michaelsena** [comment]
Separately, I assume we'll want to provide participants with a boilerplate react app with these components and structure and logic already all set up? Who will build that? Will you build a rough implementation this upcoming sprint @oed, and then perhaps the following spring @oznekenzo can build out the UI and make the components?

Another question, where is the line between what we want to provide and what we want people to create/integrate?

**Comment by oed** [comment]
I think it looks good, but I don't think we should expect the experience to be super smooth, just good enough. And yeah, was thinking I'd start with a rough impl this sprint or the next :) Can sync with kenzo if needed.

Yeah exactly, the plan is to have the participants in the workshop only implement the 3box-js code. So no contract deployment or frontend development. I think basically what is most valueable is if people get to just plug in the neccesary calls to 3box-js and then have the UI magically work.
