### ISSUE TITLE
Error in registration and getting profile

### ISSUE THREAD

**Issue by spetsmash** [3box/3box#672]
Hello. Trying 3Box and  3Box: 
after trying several times this tool can't be integrated in our projects as it doesn't working properly.

I have an instance of test UI working with this 3Box. This is the next steps of "user experience" I had:
1. I have passed registration on the https://3box.io/hub and created profile
2. Then I pasted my address in the form to get profile and response was that this user is not exist. https://prnt.sc/ogyazp
3. After I go to the web site to check if me profile exist it shows me an error http://prntscr.com/ogybj4

5. For address, that was hard coded in example profile it getting like this http://prntscr.com/ogyaaa

Seem for now there is some problem with keeping registered users in the system.

**Comment by oed** [comment]
Thanks @spetsmash, responded to you on our discord. Let me know if you didn't see that message!
