### ISSUE TITLE
Ghost Chat API

### ISSUE THREAD

**Issue by oed** [3box/3box#675]
## Introduction
Currently 3Box supports building chat like system though the threads api. However, for building things like trollboxes, or online lists, etc. threads are not the best fit. Ipfs has a feature called `pubsub`, which is a system for passing messages between peers. Pubsub can be used to create an ephemeral chat system where messages are not persisted anywhere in the network, rather they are just sent across once and seen by anyone online at that point.

## API
This system would most likely fit best under Spaces. Each message sent in the system would be signed by a space3ID (subDID). The api could looks something like:

```js
const chat = await space.joinChat('name-of-chat-room')

chat.on('message', messageCallback)

chat.on('user-joined', joinedCallback)

chat.on('user-left', leftCallback)

// returns an array of space-3ids of the users
const userList = chat.onlineUsers()
```

The parameters of the callback functions would be as follows:
```js
// user - String - the space-3id of the user making the post
// message - String or Object - the message sent by the author
messageCallback (user, message)

// user - String - the space-3id of the user joining
joinedCallback (user)

// user - String - the space-3id of the user leaving
leftCallback (user)
```

## Peer discovery
Right now 3Box peers are only connected to the 3Box pinningNode. This makes it impossible for nodes to discover each other and send each other pubsub messages. We need to set up a [Rendezvous](https://stackoverflow.com/questions/52910503/how-can-i-get-a-libp2p-rendezvous-server-running) server for peers to find other peers, we also possibly need to enable the DHT (which is still an experimental feature in js-ipfs). Another alternative is to use the **Delegated peer and content routing** described [here](https://github.com/libp2p/js-libp2p/tree/master/examples/delegated-routing) and [here](https://github.com/ipfs/js-ipfs#configuring-delegate-routers).
An important thing to consider is if we want to connect to the default ipfs nodes which would make us part of the entire ipfs network, or if we want to keep our nodes only connected to each other and not the rest of the ipfs network.

## Message signing
We want to make sure that the messages posted in the chat are from the user that they claim to come from. We can do this by internally signing the messages as JWT claims, which 3box already supports. These JWTs can be signed by the space-3id for easy verification. This would all happen behind the scenes in the api though so that consumers of the api wouldn't need to worry about it.

## Implementation
To implement this we can likely use `ipfs-pubsub-room` as suggested by @ghiliweld [here](https://gist.github.com/ghiliweld/879408f9a03badef7a59907e11246ebd) or something similar like  [orbit-db-pubsub](https://github.com/orbitdb/orbit-db-pubsub) which is already a dependancy for us, but looks more limited. 

### Requirements
* Should extend the 3box-js library using the api defined above
* Should be able to find all other peers on the same chat within a reasonable time bound
* Should work well in most browsers (including mobile dapp browsers)

### Testing
The 3box-js repo has an example-dapp which can be extended in order to test the chat functionality. 
**Ways to test:**
* Implement tests as part of 3box-js, similar to how other tests are set up in the 3box-js repo now we can set up two ipfs nodes in the test file and have them communicate with each other.

In all of the examples below different 3box accounts are used to send messages in each browser.
* Two browsers same computer, e.g. chrome and firefox
* Two browsers same network but different computers, e.g. phone and desktop connected to the same wifi
* Two browsers different networks, e.g. phone not on wifi and computer on wifi etc
* Come up with more test cases? \o/

Before we go ahead and try to get everything working with discovery, we could test the api by directly connecting nodes. This would allow us to make sure the the API is fully functional by itself.

### Questions to answer during the implementation process
- Should we connect to the rest of the ipfs network or keep our network separate?
    - What are the tradeoffs?
    - What are the differences in performance?

**Comment by ghiliweld** [comment]
In terms of peer discovery would using something like [orbit-core](https://github.com/orbitdb/orbit-core/blob/master/API.md) do the trick? Instead of having multiple ipfs nodes communicate with pubsub, we could keep using the 3box pinningNode even without a Rendezvous server (still in the process of verifying this but I think it might work).

When you `joinChat` under a `space` you join a `channel` on orbit-core, the channel name can be the spaceID. We can then watch for any messages in the channel. The channel api is very similar to the proposed api above so it would work quite well.

So all that's left is checking whether it work by using the same 3box pinningNode and if not we can set up the rendezvous server. I'm not sure what the DHT would be for in this case though @oed

**Comment by oed** [comment]
If I understand correctly `orbit-core` is much more heavy weight than the method I'm proposing. Basically every channel in orbit-core is an orbit-db database, which means that the chat wouldn't be ephemeral and would be persisted. So I'm not sure this actually provides any benefits over just using 3box Threads.

The core of the idea with ephemeral threads are that messages are not persisted and only exists when they are sent over the pubsub room, which also makes this system very light weight. Does that make it more clear?

**Comment by ghiliweld** [comment]
Oh I didn't notice orbit-core persisted messages to a db. Perhaps modifying something like [`ipfs-pubsub-room`](https://github.com/ipfs-shipyard/ipfs-pubsub-room) would do the trick then. I'll look into it.

**Comment by oed** [comment]
Cool, yeah that makes sense @ghiliweld. I still do think that even if we use `ipfs-pubsub-room` we need a way for peers to discover each other. Either we would need to use the DHT, or maybe use the **Delegated peer and content routing** in the upcoming [ipfs release](https://github.com/ipfs/js-ipfs/issues/2192). Might be other ways to do it more easily though!

**Comment by pgebheim** [comment]
Hello!

Great to see there's work happening here, this might relate to our Chat / Comments tasks for Augur.

Design / Product: https://github.com/AugurProject/augur/issues/2373
Engineering: https://github.com/AugurProject/augur/issues/2970

@nuevoalex @cillianhunter0

**Comment by michaelsena** [comment]
Yup you landed in the right spot @pgebheim. Ghost Chat API would be great for your site chat, and our existing threads would be good for your market chat (more like comments section).

Here's documentation on Threads which could be user for market chats. https://docs.3box.io/build/web-apps/messaging

**Comment by michaelsena** [comment]
@pgebheim I noticed that you mention wanting to persist the site chat for 24 hours. Is that the actual requirement? In the past we had talked about just syncing new messages when the user arrives at the site, which means they would get no history, only forward messages since their time on site. 

You could build a 24-hour persisted site chat with out existing threads API, just by creating a new thread every 24 hours. The downside here is if the thread gets too big syncing will be slow given current limitations in OrbitDB which they're working on.

Let me know which one would be better for you.

**Comment by oed** [comment]
Closing this in favor of https://github.com/3box/3box/blob/master/3IPs/3ip-9.md
