### ISSUE TITLE
Unable to retrieve space

### ISSUE THREAD

**Issue by azrose1** [3box/3box#727]
Hello,

I am unable to retrieve a user's space using `box.openSpace`. I am calling it in a promise chain after retrieving the box successfully with Box.openBox. I am using uPort as a provider for the address, so I am first resolving the address from a uPort identity.

```
Box.openBox(this.props.identity.address, uport.getProvider())
      .then((box) => (box.openSpace('todo')))
      .then((space) => (this.onSpaceRetrieved(space)))
      .catch((e) => {
        toast('failed to open box/space', { type: 'error' });
        console.error(e);
      })
```

An unknown exception is being generated:

```
1.chunk.js:281116 Error: An error occured while opening space: 
    at Box._callee6$ (1.chunk.js:1093)
    at tryCatch (1.chunk.js:303699)
    at Generator.invoke [as _invoke] (1.chunk.js:303918)
    at Generator.prototype.<computed> [as throw] (1.chunk.js:303752)
    at asyncGeneratorStep (1.chunk.js:8587)
    at _throw (1.chunk.js:8613)
```

The error is not descriptive at all, else i'd try to debug it myself.

**Steps to reproduce:**
1. Retrieve uPort Identity via QR code / Disclosure Request
2. Gather required signatures via uport subprovider sign requests.
3. Resolve ethereum address from uPort DID (did:ethr:... >> 0x...)
3. Bind "sync" function to a button click in react.
4. Call sync on click. Provide the resolved address. Retrieve box using `Box.openBox`
5. Attempt to open space using the reference to the box using `box.openSpace`
6. Error.

Note:
- `Box` refers to the import, `box` is a variable corresponding to the actual box.

Cheers.

**Comment by oed** [comment]
Thanks for reporting. So if I understand correctly `Box.openBox` works correctly, but `box.openSpace` doesn't work? I'm wondering if the uport ethereum provider works as intended 🤔

**Comment by digitalkitten** [comment]
I’ll test with meta mask 

Alexandra Belluscio
https://alexbellusc.io

**Comment by digitalkitten** [comment]
if i'm correct, it is failing because of the `UportSubprovider` not having `sendAsync` defined or available.

@oed does 3box utilize sendAsync during initial box/space opening consent?
