### ISSUE TITLE
Create issues in orbit-db github

### ISSUE THREAD

**Issue by oed** [3box/3box#748]
Create issues in orbitdbs github that describes some thoughts we have on improvements etc. Create issues for:

### ~Only verify identities once, should reduce time spend verifying sigs~

Cache the verified identities for O(1) verification speed.

### ~Store identities as ipfs objects, should make each entry smaller~

Possible future improvement for odb, will make each entry not having to have the whole identity object. (this is not super urgent)

### Send heads directly

Send heads on peer join directly from db, instead of waiting for the entire log to be loaded/reconciled in memory before sharing heads 

### Verify log entries once, don't verify again if loaded from memory/db

For entries that are being loaded from the "localHeads" or "remoteHead" (using `store.load()`) there is no need to verify the signatures in the log entires. Instead the data can just be directly loaded since the signatures should already have been verified once. Entries that are replicated from the network still need to have their signatures verified.

### Update to odb messaging layer
Right now we are using a modified version of orbitdb in 3box-pinning-node. This should be documented as an issue, with an example pointing to our code. A PR can come later.

### Follow up on:

[https://github.com/orbitdb/orbit-db/pull/688](https://github.com/orbitdb/orbit-db/pull/688)

**Comment by oed** [comment]
Ipfs-pubsub-room seems like a better version of orbitdb-pubsub. Create an issue to ask about maybe updating to use that instead.

**Comment by oed** [comment]
Created issues:
https://github.com/orbitdb/ipfs-log/issues/273
https://github.com/orbitdb/orbit-db-identity-provider/issues/48

**Comment by michaelsena** [comment]
Also make an issue that: add functionality should have a queue

**Comment by zachferland** [comment]
will add monday

**Comment by zachferland** [comment]
https://github.com/orbitdb/orbit-db/issues/752

**Comment by zachferland** [comment]
https://github.com/orbitdb/orbit-db/issues/753

**Comment by zachferland** [comment]
Last one not worth opening issue, eventually best explained with pr, but low prio right now
