### ISSUE TITLE
Add @types/3box

### ISSUE THREAD

**Issue by bkawk** [3box/3box#810]
Please, can you add typings for 3box?

error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2f3box: Not found".

**Comment by eshohet** [comment]
I'd like to bump this - it would be super helpful for us to have this.

Happy to help anyway I can - I'm already working on some types now, but would love some support!

**Comment by Shikanime** [comment]
I published the @types, feel free to contribute if there is a problem.
