### ISSUE TITLE
Slim down pinning-node

### ISSUE THREAD

**Issue by oed** [3box/3box#816]
Right now the pinning node still contains the code for the rest api. This is not needed anymore since a separate repo 3box-api is being used to provide this functionality. Removing the api code from the pinning-node will simplify it a lot.
This work is also needed so that we can effectively update orbitdb and ipfs.

**Comment by oed** [comment]
@zachferland Can you please provide more detailed stories for this epic?

**Comment by zachferland** [comment]
@oed thanks for the adding the stories here, looks good :+1:
