### ISSUE TITLE
Uncaught error while trying to create a space containing the dot character

### ISSUE THREAD

**Issue by deiu** [3box/3box#837]
Hi,

While testing the spaces API today, I found that it fails to create spaces using a name that contains the dot (.) character. It would be really helpful to either add validation or to put a notice in the documentation that lists the allowed characters.

This was done in the browser, using `https://unpkg.com/3box/dist/3box.js`.

```js
const space = await box.openSpace("my.dapp")

3box.js:329 Uncaught (in promise) Error: An error occured while opening space:  Error: An error occured while opening space: 
    at Box._callee2$ (3box.js:328)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as throw] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _throw (asyncToGenerator.js:29)```

**Comment by oed** [comment]
Hey, yeah having a `.` in the space name will not work. We should throw an explicit error when someone tries to do this!

Thanks for reporting!
