### ISSUE TITLE
AWS Cost estimates

### ISSUE THREAD

**Issue by msterle** [3box/3box#844]

**Comment by dazuck** [comment]
Starting point of questions that need to be answered in load testing. Clear outputs on these can feed into a scenario models:
 
1. How does scaling up each of these primary factors (independent of the others) scale cost
* number of users (active, new, total) 
* average number of sets per user 
* average number of gets per user 
* average size of transactions

2. How significantly do these adoption variables impact our cost scaling
* whether usage is highly concentrated (a few users) or more distributed (most users similar) 
* number of nodes in the network 
* product usage: public vs. private KV store vs. threads 

3. Does cost structure change meaningfully if 
* there are fewer, bigger DBs with shared access vs. more, smaller DBs with more limited access
* [feels like there are others to add here]

Other factors presumably outside of load testing
* % assumed performance improvement over time 
* % of nodes we (3Box runs) 
* % of data gets happen from local store

cc @michaelsena @oed @zachferland @msterle for visibility
