### ISSUE TITLE
Get `peer.exchanged` event PR merged into orbitdb

### ISSUE THREAD

**Issue by msterle** [3box/3box#876]
Requires https://github.com/orbitdb/orbit-db/pull/606 and https://github.com/orbitdb/orbit-db-store/pull/38 to be merged and released

**Comment by msterle** [comment]
PR opened in orbit-db-store repo: https://github.com/orbitdb/orbit-db-store/pull/84

**Comment by oed** [comment]
Linking for context: https://github.com/3box/3box-pinning-node/issues/258

**Comment by msterle** [comment]
See additional discussion here: https://github.com/3box/3box-pinning-node/issues/258
