### ISSUE TITLE
Coordinate with Austin Griffith on design specs for ETHDenver DAO

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#880]
This includes:
- Edit Profile functionality
- Leaderboard functionality

**Comment by oznekenzo** [comment]
You'll be setting up this meeting right @michaelsena ?

**Comment by michaelsena** [comment]
@oznekenzo guess this is now technically in progress right?

**Comment by oznekenzo** [comment]
Mmmm sure - I don't know how aware of this he is but seems like someone on their side is looking into design
