### ISSUE TITLE
Career page update

### ISSUE THREAD

**Issue by dazuck** [3box/3box#894]

**Comment by oznekenzo** [comment]
Do 1 @ minimum https://www.notion.so/threebox/Company-careers-page-889f5b800e8b403fb6567b5d395e1f91?d=94c452fa-dc91-42ef-bf75-949f00a7d5d0
2, 3 if time

- [ ] 1
- [ ] 2
- [ ] 3

**Comment by oznekenzo** [comment]
can recreate or reopen for task #3
