### ISSUE TITLE
Spec out pinning node peering

### ISSUE THREAD

**Issue by msterle** [3box/3box#899]
In the current setup, as described in [ref #1](874), external pinning nodes bootstrapped to the 3box pinning node will only receive a subset of pubsub messages (those passed to the host to which the websocket connection has been forwarded). The interim solution of using the rendezvous server is not adequate because of the delay between connecting to the rendezvous server and connecting to client peers, particularly given the current 3box-js method of pinning, which sends pinning requests immediately upon joining the swarm.

Two solutions have been proposed:
1. Add another messaging layer between 3box pinning nodes to propagate pubsub messages in the `pinning-room` channel between these nodes, and so reach the external pinning nodes
  Limitations: additional messaging layer
2. Remove the load balancer and expose all 3box pinning nodes as unique peers
  Limitations: peer discovery (internal and external), maintaining a consistent bootstrap list

I agree that the first is the more stable option (see [ref #2](https://www.notion.so/threebox/Next-direction-infra-notes-d44528de3d0a4024b327bb003f5a7a59)), and should be pursued next. However, I believe that by propagating libp2p pubsub messages through different layer, we are essentially recreating functionality built into ipfs-cluster, and so think exploring this existing tooling is important. I also have concerns about using shared resources, and think the implications should be further explored - if this will lead to concurrency issues, it would point to another reason for using ipfs-cluster, as well as handling orbitdb differently.

Questions to be answered:
- What are the implications of running multiple ipfs nodes with the same S3 storage backend at scale (are there concurrency issues? What would an alternative look like?
- What are the implications of having a shared orbitdb cache?
- Can orbitdb run with a separate ipfs process/container? What are the restrictions or disadvantages of doing so?
- Although IPFS pinset management would be handled by ipfs-cluster, how would the orbitdb swarm handle sync requests?

Bonus questions:
- Why does our pinning node frequently use up all available resources, independent of traffic?

ref:
1. #874
2. https://www.notion.so/threebox/Next-direction-infra-notes-d44528de3d0a4024b327bb003f5a7a59

**Comment by zachferland** [comment]
Feels like this could be broken down and/or prioritized a bit differently. This problem alone isnt really sufficient in my opinion to drive option 2. Should we prioritize a solution first to the issue before other research work? wouldn't want the options for others running pinning node to be blocked for extended time. 

Fairly sure it is pretty minimal to solve current issue, just two hooks on an interface we have available already. Would just use current redis pubsub to relay messages, with an additional pinning room topic. When node receives PIN_DB, pub to redis. Another redis on message listener, when receive PIN_DB (from internal redis), relay through libp2p. (don't act on message, ie open dbs or anything). 

But besides this issue, there is definitely other potential reasons to consider option 2 again, especially as we start to change past held assumptions, and move to a more open and connected network.

For one the current internal messaging layer isn't perfect. It mostly assumes right now that each network formed with each node is partitioned (ie clients just connect to node, each set creates their own network), so its fine to relay message with out thought from one network to another. This of course is not the case going forward and already doesnt hold as peers connect to each other. When we have this network overlay (or one net), we may be redundantly sending messages, or even causing loops. 

Another major driver for some changes i think are the ability to run a 3box node against existing ipfs infra. Definitely some refactoring there and issues to be considered. Already captured here as you mentioned, but also doesnt necessarily drive option 2 alone. (and could likely be prioritized separately before other changes)

Should consider if the pinning room is really the long term solution to how we will coordinate opening, syncing, and pinning on the network. Especially if one of the main drivers for a change.

Some notes on ipfs cluster: 

IPFS cluster isnt necessarily a way to scale up, ie from 1 node to many, in the traditional sense (meet/balance load). It mainly grows guarantees around availability and durability of data in a given pinset. It is just a consensus layer for the pinset values. 

Alone it doesnt give you much in scaling up to meet traffic demands or pubsub (libp2p) traffic. Potentially though when paired with other layers of orchestration (but could require as much custom tooling/services as we currently see now) 

in many ways we possibly wouldnt want to rely on libp2p pubsub internally on a cluster of our nodes entirely within our own domain. The overlay operates on the assumption on running in a open context. Which could rely on overly aggressive routing, relaying, coordination overhead, etc. A set of open nodes would have some interdependence if all listening to same topic, as they would redundantly relay messages to each other. So a lot of traffic for one topic on one node could cause some fixed load across all nodes in cluster (vs could be independent with internal layer). I think eventually transports, routing, etc for all these models eventually end up in libp2p. 

running indexing/api layers would be more expensive (resources, time, coordination) if the storage layer was not singular, but depends exactly what is looks like

Some notes on storage layers: 

helpful to look storage layer pieces separately, ie the blockstore of an ipfs repo should not have an issue being shared. And depends in which storage layer they are run against. (ie even if running multiple different nodes, would still consider writing data blocks to shared layer still)  While you would not be able to share the pinset store, or generally run pinset gc on the blockstore. But anyways would really like better ideas of the differing  hard guarantees here and issues at scale other than our empirical evidence of it just working so far.

im more concerned with orbit data right now than ipfs, which is just the log heads. There is race conditions where a head ref could be lost. Not all heads, just if multiple.
