### ISSUE TITLE
Figure out what is causing CPU spikes in pinning-node

### ISSUE THREAD

**Issue by oed** [3box/3box#910]

**Comment by zachferland** [comment]
May not be high enough prio for this sprint, also would like more of @msterle take, since have given this a first go already. I captured what it could be already (probs have to find that again), but didnt completely confirm. Failure state captured but wasnt clear what led to that state in orbitdb.

**Comment by zachferland** [comment]
Also likely not degrading performance, just consume extra resources. So not high prio until more people run with any sort of scale.

**Comment by michaelsena** [comment]
closing, duplicate
