### ISSUE TITLE
Some profiles not loading, possibly corrupted by gitcoin error

### ISSUE THREAD

**Issue by msterle** [3box/3box#921]
Some users are reportedly unable to load their profiles on the Hub, possibly because they also use gitcoin with the same account, and their profiles may have had unexpected data inserted.

Reports:
https://discordapp.com/channels/484729862368526356/485438052903288832/675312141879738370

Possibly related to:
- https://github.com/3box/3box-dapp/issues/610#?repos=139279908,123418089,122765608,145133349,145592766,146687169,146688532,151621734,158471466,158455119,160876370,161105074,162613112,167886255,166464095,168911637,154979770,174195970,179497499,178844785,163501493,184584345,187688771,188829916,196352247,202930893,197326552,206198357,206819182,200551191,219899571,219899761,228673888,220489929
- https://github.com/gitcoinco/web/issues/5960

**Comment by balasan** [comment]
may be related (at least it seems to have started happening once I connected my account to gitcoin)

I'm getting an error when trying to call `Box.openBox` with that specific address

```
Store.js:123 TypeError: Cannot read property 'verify' of undefined
    at Function.verify (keystore.js:189)
    at Keystore.verify (keystore.js:182)
    at Identities.verify (identities.js:42)
    at Function.verify (entry.js:80)
    at verify (log.js:379)
    at log.js:387
    at async pEachSeries (index.js:8)
    at async Log.join (log.js:385)
    at async Replicator.onLoadCompleted (Store.js:109)
```

**Comment by michaelsena** [comment]
Thanks for your report @balasan. cc'ing @owocki, the Gitcoin star trooper here to help us figure out what's going on. Kevin and I chatted briefly about this at ETHDenver, and seems to make sense that they might be saving some data somewhere that prevents the profiles from syncing or loading.

**Comment by balasan** [comment]
My particular issue got resolved the following day with a new 3box-js version 1.17.0
So this may be solved now?
