### ISSUE TITLE
Identity failure points of shared orbitdb cache

### ISSUE THREAD

**Issue by msterle** [3box/3box#942]
We use a shared redis store for our pinning nodes' orbitdb caches, and this is not expected to have concurrent access.

*Note: is `orbit-db-storage-adapter` relevant?* 

AC:
Document any potential concurrency issues and propose potential solutions where possible.

**Comment by zachferland** [comment]
https://github.com/orbitdb/orbit-db-storage-adapter is somewhat, it doesn't solve the problem here, but that was partly created to support what we were doing. We used a redis orbit cache before this existed, to migrate would have to do a redis key migration, and limits control a bit.

**Comment by zachferland** [comment]
some notes 

the nice thing in general is orbit crdts join operations over the heads array is commutative and idempotent (ie writing heads to store with a join), the only difficultly i guess is the join operation requires the entire log state in memory to join, we cant write a function just over the current heads and new heads, only over the entire log. Ideally only one in memory instance of the log would consume all updates. But in general this has not been an issue  with multiple instances, as long as the updates are reliably relayed internally, as they will shortly converge to same values, same true for any clients connected. So pretty stable when dbs are open, i think concurrency issues could arise during the inbetween states, like in process of opening/closing of same db across nodes.

ie

Node A db open with log  [A, B, C, D], orbit cache = D
Node A receives E at same time Node B is opening 
Node B read orbit cache = D, and loaded [A, B, C, D] before Node A wrote orbit cache = E
Node B not subscribed to log yet, doesnt get entry E. Clients connected to B dont get E, they write values F, G. Node B writes orbit cache = G. Now log here equals [ A, B, C, D, F, G]. And maybe Node A closed already. Now entry E is lost.

Maybe dependent on actual ordering of functions in orbitdb, but still likely holds in some form.

**Comment by msterle** [comment]
As described by @zachferland above, this is not an issue in our current setup because all update messages are sent to all databases that are open, and so are independently applied to each, and the same results written to the store by each. These should match up under normal usage.

However, if two pinning nodes with the same database receive different update messages, the later one will be applied without merging in the former. This is because orbitdb relies on remote heads stored in memory instead of fetching them from the cache every time. This can be seen by running `redis-cli monitor` on the orbitdb cache redis instance - a `set` operation is received without a `get`.

If we want to move away from sending all updates to all dbs that are open (for example, by moving away from pubsub messaging and towards more explicit routing for load balancing) there are two options to mitigate this:
- inside `orbit-db-store`, calling `store.syncLocal()` to fetch heads from the shared cache and merge them before writing to the cache
- in the pinning node, using redis pubsub to watch `set` event on open database entries, and calling `store.syncLocal()` on those databases when updates to the cache occur

**Comment by zachferland** [comment]
don't quite follow i think, or lost earlier context, does paragraph two reference a situation that could occur now? or saying assuming we didnt have a reliable transport layer between open dbs then could end up with diff values. 

Are the bulleted options if NOT moving to towards explicit request/message routing (db open in one place) right?

**Comment by oed** [comment]
> calling `store.syncLocal()` to fetch heads from the shared cache and merge them before writing to the cache

We are not doing this? I assumed we where. There is an option that you can pass when you open the DB to do this automatically.

**Comment by msterle** [comment]
@zachferland 

> don't quite follow i think, or lost earlier context, does paragraph two reference a situation that could occur now? or saying assuming we didnt have a reliable transport layer between open dbs then could end up with diff values.

Yes, it could in practice occur now, but I'm not trying to be alarmist, because it hasn't become an issue yet. Under our current setup, if there is a failure where pinning nodes don't receive identical messages, they will diverge, and the last write will become the value stored in the orbit-db cache. This could occur for example if as a pinninng node loses connection to redis, reconnects, but missed messages during the process (redis pubsub isn't considered a reliable delivery method because it doesn't have any message queues - it's fire and forget).

> Are the bulleted options if NOT moving to towards explicit request/message routing (db open in one place) right?

This would be good practice either way, at the potential cost of an unknown impact on sync speed. This is balanced against the risk of it occurring, which is directly related to how many nodes have the database open at the same time - under the load balanced method, there will be a good chance simultaneous writes occur if the same database is opened by two different clients, since requests are handled in a round-robin way. Under the workers model, the chance of a database being opened multiple times is down to queue sync failures (in the case of pubsub workers, an IPFS pubsub failure, or a delay beyond the configured time limits).

@oed 
The `synclocal` method isn't called in all cases where the cache is written to - the case where I was seeing failures is here: https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L119
