### ISSUE TITLE
Setup repo for iframe content

### ISSUE THREAD

**Issue by oed** [3box/3box#945]
Could maybe use old 3box-account repo?

Also set up testing environment for testing the iframe together with 3box-js

**Comment by michaelsena** [comment]
@zachferland I think we should probably rename the `3box-account` repo to `3id-auth-iframe` or just `3id-auth`, and transfer it to the protocol org once that's live. Thoughts?

**Comment by michaelsena** [comment]
@zachferland on second thought, might make sense to call it `3id-connect` (if we think in the future we may have other iFrames for different DID methods) or just `connect` (if we don't)

cc @oed
