### ISSUE TITLE
Multisize-image

### ISSUE THREAD

**Issue by oed** [3box/3box#994]
# Multisize-image

> A tool for handling images better in ipfs

Storing an image in IPFS right now is not optimal for many use cases, but IPLD can change that. **Multisize-image** is a proposed tool to take one image and resize it to multiple images and finally link them together using IPLD.

One of the prolems we've been running into while building 3Box is the problem of image size. We allow users to upload a profile picture to ipfs, we then put the CID of this image into the users profile. If the user uploads a large picture every site that now loads this user profile will take a while to load since the image is huge. This becomes especially apparent when a site is displaying a lot of user profiles and displaying the images in a small format. In the worst cases the site might load a 1000x1000 px image and display it as 20x20 px. 

## Image resizing

The obvious way to deal with this is to resize the image. However, for different use cases we might want to get a different size for the image. So just resizing it once to a specific smaller size is not optimal. Instead we might want to encode it to a few different predefined sizes: `XL`, `L`, `M`, `S`.

## Image bundling using IPLD

Given that we did the resizing as defined above we now have five different images. It would not be great to have to store a bunch of references to all of these sizes in a users profile for example. Better would be to have one common reference to all of them. IPLD can solve this by creating a "wrapper" object.

    {
      original: <CID-of-original-image>,
      xl: <CID-of-xl-resize>,
      l: <CID-of-l-resize>,
      m: <CID-of-m-resize>,
      s: <CID-of-s-resize>
    }

This wrapper object would get it's own CID and we could reference the `M` size by requesting `<cid>/m` from IPFS.

## Open questions

There are a few open questions given the information above.

### Optimal set of sizes

Should the different sizes always be predefined or should it be configurable? 

If it's a smaller original image, should it be resized to be larger to match XL?

If not, how do you know which sizes are available for this image?

### What tool to use for resizing

What already existing libraries could be used to create this resizing tool?

Is this software something that could run efficiently in a browser or does it need to happen server side?

### Library api

What's the correct api for this library?

What's the correct way to fetch an image of a given size on a site?

### Other considerations

Are there any other things that need to be considered?

**Comment by Samyoul** [comment]
This is a great plan, I really like it.

**Comment by Samyoul** [comment]
### Optimal set of sizes

>Should the different sizes always be predefined or should it be configurable?

I think predefined default with the option to configure if required.

---
>If it's a smaller original image, should it be resized to be larger to match XL?

No. This could look really ugly.

---
>If not, how do you know which sizes are available for this image?

The `CID` could be `nil`.

**Comment by Samyoul** [comment]
### Library api
>What's the correct api for this library?

**Constants**
File size names ( `FSN` ):
- `O` string
- `XL` string
- `L` string
- `M` string
- `S` string

**Variables**
Sizes:
- `XL` uint
- `L` uint
- `M` uint
- `S` uint

**Methods**
- Upload( `filename` )
- Get(`IPLD Wrapper ID`, `FSN`)
- Update() ?

>What's the correct way to fetch an image of a given size on a site?

I imagine the call to be made like so, `Get(IPLD Wrapper ID, FSN)` . If in the case that the requested size doesn't exist return `nil`.

**Comment by Samyoul** [comment]
### What tool to use for resizing
>What already existing libraries could be used to create this resizing tool?

I think that this could be done fairly simply using js `canvas` and `context`, rough example:

```js
// Make a new FileReader.
const fr = new FileReader();

// Read image for upload using the FileReader.
fr.readAsDataURL(originalImageLocation);

// Make a new Image object
const img = new Image();

// Set the result of the FileReader as source for the image.
img.src = event.target.result;

// Make a new HTML5 Canvas element
const canv = document.createElement('canvas');

// Set the width and height of the canvas, these dimensions will be the resize values
canv .width = width;
canv .height = height;

// Make a context object to draw the image onto the canvas.
const ctx = canv.getContext('2d')

// Draw the image onto the canvas. Make sure to match the width and height of the new image with the resize dimensions.
ctx.drawImage(img, 0, 0, width, height);

// Export the canvas
var data = canv.toDataURL(mime);
```

>Is this software something that could run efficiently in a browser or does it need to happen server side?

Would need to do some load testing but this seems to be efficient enough.

**Comment by oed** [comment]
Thanks for diving in @Samyoul. Looks great so far! I tried to find you on our discord to send you a message, are you on there?

> I think predefined default with the option to configure if required.

Yes!


> Library api

This looks really great!
Questions:
* Does **Put** return the CID of the IPLD Map?
* What does **Update** do? 


> > Is this software something that could run efficiently in a browser or does it need to happen server side?

> Would need to do some load testing but this seems to be efficient enough.

Is it possible to do something that works in both nodejs and browser? Would be nice to have the optionality to run in both client and server side.

**Comment by Samyoul** [comment]
>• Does Put return the CID of the IPLD Map?

Yes, sorry I should have defined the returns. I will add these later. 


>• What does Update do?

I can't think of a way for update to work how I first thought so I think it should be removed as we've discussed on discord.

> Is it possible to do something that works in both nodejs and browser? Would be nice to have the optionality to run in both client and server side.

Hmm, I need to think about this and see what is possible.

**Comment by oed** [comment]
The Textile team have written an image resizer in go. If we're building a servier side service for resizing their code could be useful.
    https://github.com/textileio/go-textile/blob/master/mill/image_resize.go
    https://github.com/textileio/go-textile/blob/master/mill/image_exif.go

**Comment by Samyoul** [comment]
I've read through these and I don't think that they would be very helpful. All of the image manipulation is handled by the native `image` package.

We could use the node canvas package, and do image manipulation using that on server side deployments.

**Comment by oed** [comment]
That makes sense @Samyoul. Thanks for having a look!

**Comment by bmann** [comment]
Thanks for the pointer @oed -- we've got @ellttBen investigating work in this space. We're focusing on the metadata and making this work "locally" first in a developer's local environment.

Also, Pica looks to be a good in browser resizer https://github.com/nodeca/pica 

The main point I'd like to collaborate on is agreeing on file size naming / linking.

**Comment by ellttBen** [comment]
Hello everyone! As mentioned by @bmann, I'm working on a similar problem right now. Using IPLD's built-in paths seems to me the right idea. I can see two main ways to implement the wrapper object.
- The first is to use a UnixFS directory node, which points to differently sized versions of the image.
- The second is to use IPLD linking within the original node. This means that `cid0` could point directly to the original, whereas `cid0/WxH.jpg` could point to another version. In go-ipfs this means running `ipfs add cat.jpg` which gives us `cid0`, `ipfs add WxH.jpg` which gives us `cid1` and then running `ipfs object patch add-link <cid0> "WxH.jpg" <cid1>`, if you want to try it out.

Regarding the naming scheme, I think being explicit about width and height makes the scheme more legible and flexible for our purposes.

**Comment by oed** [comment]
Hey @ellttBen Thanks for you're comment!

Both of you're suggestions uses the `dag-pb` codec format. I believe that the ipfs team is putting more effort an focus into the newer `dag-cbor` codec. This is also the codec that is suggested to be used above. 

I'm a little torn about you're suggestion with including height + width because it will be hard to enforce a specific size especially if you allow the user to upload images of various proportions. In my app, how would I know which size to load if there are a lot of different options? I guess this is a question of where we put the logic to make this descision. What you are suggesting pushes the decision out to the app, while what I suggested above makes the decision happen in the library.

**Comment by bmann** [comment]
This should get done at the app layer. Different apps are going to want different sizes. Some will want squares. Some will generate 3 different social preview sizes.

Most apps I’ve seen include a cropping selector for eg avatar sizing. 

Making this on width and height supports the largest number of use cases and that the most number of image thumbnails are already created. 

There’s probably some variants like restricting on width only or height only, and there are some algorithms that do feature aware cropping, but I think the goal should start by thumbnailing size variants.

**Comment by oed** [comment]
Totally @bmann, thanks for clarifying! Any thoughts on the different codecs?

**Comment by bmann** [comment]
Re codecs: I’ll leave that to @ellttBen to research, although those examples were literally IPFS command line examples I believe.

**Comment by oed** [comment]
@ellttBen A good resource for understanding IPLD can be found here: https://github.com/ipld/specs
There is an updated version of ipld being built for go-ipfs which can be found here: https://github.com/ipld/go-ipld-prime

I believe the dag-pb format is going to be phased out in favor of dag-cbor which the above library primarily focuses on.

**Comment by ellttBen** [comment]
@oed Thanks for the pointers, I'll do some research on the different codecs. However, I believe this should be a question to be solved on a per-implementation basis. In order to read and write to ipfs I'll be using reference ipfs libraries which are compatible with both dag-cbor and dag-pb codecs. The fact that the codec being used is specified at the beginning of ipfs [CIDs](https://cid.ipfs.io/) ensures retro-compatibility for the foreseeable future. Right now, since go-ipfs uses dag-pb by default, I'll be using it for my own implementation, at least to begin with. 

However, the <cid>/W_H.<ext> schema doesn't presuppose one or the other and is the only requirement to interoperability between implementations. Regarding that I perfectly agree with @bmann's argument that specifying width and height is the most flexible approach. 

It might be even more flexible to add *wildcards* to the representation. For example, if a client requires a version that is 128 pixels high, not knowing the aspect ratio of the image, the CID could be <cid>/-_H.<ext>. This would mean that a given version would have its CID linked to three times under the main image (at W_-.<ext>, W_H.<ext>, _-H.<ext>). I don't know how useful that would be in practice however, and it might be smarter to deduce the required dimensions client-side using the original's dimensions that could be mentioned as metadata on the original node.

**Comment by oed** [comment]
Ok, makes sense @ellttBen. Excited to see what you come up with! :)

**Comment by ellttBen** [comment]
Hello, just a quick update. I've detailed [here](https://github.com/fission-suite/basquiat#proposed-metadata-schema) my proposal for an expandable metadata schema for images. If you have any suggestions for improving the spec, please don't hesitate to open an issue on the repo.
While you're there, you might want to play around with *basquiat*, which implements a part of the spec.
